"use strict";
const fs=require("fs");
const assert=require("assert");
const read=(p)=>fs.readFileSync(p,"utf8");
const client=read("client/app.js");
const html=read("client/index.html");
const application=read("server/application.js");
const sw=read("client/sw.js");
const styles=read("client/style.css");
assert(client.includes('CLIENT_VERSION = "0.7.0-alpha7.7"'));
assert(html.includes('Stability & Security v0.7.0-alpha7.7'));
assert(html.includes('id="group-settings-modal"'));
assert(client.includes('class="edited-meta">изменено'));
assert(client.includes('data-group-role'));
assert(application.includes('GROUP_MEMBER_ADDED'));
assert(application.includes('GROUP_DELETED'));
assert(application.includes('req.method==="PUT"'));
assert(application.includes('message.editedAt'));
assert(sw.includes('fibrochat-shell-v0.7.0-alpha7.7'));
assert.ok(application.includes('/api/calls/signal'), 'Call signaling endpoint is missing');
assert.ok(application.includes('calls.audio.webrtc.v1'), 'Call capability is missing');
assert.ok(client.includes('startAudioCall'), 'Outgoing audio call client is missing');
assert.ok(client.includes('acceptIncomingCall'), 'Incoming audio call client is missing');
assert.ok(client.includes('queuedCandidates'), 'ICE candidate queue is missing');
assert.ok(client.includes('startCallTone'), 'Call tone generator is missing');
assert.ok(application.includes('/api/calls/config'), 'Call ICE config endpoint is missing');
assert.ok(application.includes('TURN_URLS'), 'TURN environment configuration is missing');
assert.ok(html.includes('id="call-modal"'), 'Call modal is missing');
assert.ok(html.includes('id="call-button"'), 'Call button is missing');
assert.ok(styles.includes('Alpha 7.1: message actions never overlap'), 'Message action layout fix is missing');
assert.ok(styles.includes('FibroChat v0.7.0-alpha7.7'), 'Alpha 7.4 UI layout is missing');
assert.ok(styles.includes('--alpha74-dock-height'), 'Bottom navigation safe-space variable is missing');
assert.ok(styles.includes('position:fixed;') && styles.includes('.workspace-alpha74 .fibro-navigation'), 'Fixed bottom navigation is missing');
assert.ok(styles.includes('padding-bottom:calc(var(--alpha74-dock-height)'), 'Page navigation safe space is missing');
assert.ok(read('client/ui-shell.js').includes('workspace-alpha74'), 'Alpha 7.4 workspace class is missing');
assert.ok(application.includes("/api/invite-requests"), "Smart invite request endpoint is missing");
assert.ok(application.includes("INVITE_REQUEST_APPROVED"), "Invite request approval is missing");
assert.ok(client.includes("handleSmartInviteLink"), "QR deep-link handler is missing");
assert.ok(client.includes("createOnboarding"), "Onboarding wizard is missing");
assert.ok(styles.includes("smart invitations and guided onboarding"), "Alpha 7.5 styles are missing");
assert.ok(client.includes('type==="attachments"') || client.includes('content.type==="attachments"'), "Multi-file attachments are missing");
assert.ok(client.includes('previewAttachment'), "Inline attachment preview is missing");
assert.ok(client.includes('voiceWaveformMarkup'), "Voice waveform UI is missing");
assert.ok(client.includes('data-voice-speed'), "Voice playback speed control is missing");
assert.ok(client.includes('data-load-older'), "Lazy message window control is missing");
assert.ok(application.includes('/api/typing'), "Typing activity endpoint is missing");
assert.ok(client.includes('chat:activity'), "Typing realtime event is missing");
assert.ok(styles.includes('Messenger Experience'), "Alpha 7.6 styles are missing");

// Alpha 7.6.1: super admin lifetime subscription must be enforced server-side and visible client-side.
assert(application.includes('if(user.role==="super_admin") return "active"'));
assert(application.includes('auth.user.role!=="super_admin"&&auth.user.subscriptionEndsAt'));
assert(application.includes('subscriptionLifetime:user.role==="super_admin"'));
assert(client.includes('Подписка: бессрочно'));
console.log("Alpha 3–7.7 regression assertions: true");

// Alpha 7.7: stability, rate limiting, hardening and diagnostics.
assert.ok(application.includes('security.rate-limit.v1'), 'Rate-limit capability is missing');
assert.ok(application.includes('/api/admin/diagnostics'), 'Admin diagnostics endpoint is missing');
assert.ok(application.includes('enforceApiRateLimit'), 'Global API rate limiter is missing');
assert.ok(application.includes('INVITE_RATE_LIMITED'), 'Public invite rate limiter is missing');
assert.ok(application.includes('Content-Security-Policy'), 'Static CSP is missing');
assert.ok(application.includes('Permissions-Policy'), 'Security permission headers are missing');
assert.ok(client.includes('loadDiagnostics'), 'Admin diagnostics UI is missing');
assert.ok(html.includes('id="diagnostics-summary"'), 'Diagnostics panel markup is missing');
assert.ok(application.includes('canAdminManageTarget'), 'Admin privilege boundary helper is missing');
assert.ok(application.includes('recentServerErrors'), 'Recent server error diagnostics are missing');
