"use strict";
const fs=require("fs");
const assert=require("assert");
const read=(p)=>fs.readFileSync(p,"utf8");
const app=read("client/app.js");
const html=read("client/index.html");
const server=read("server/application.js");
const sw=read("client/sw.js");
assert(app.includes('CLIENT_VERSION = "0.7.0-alpha6.1"'));
assert(html.includes('Conversation UI v0.7.0-alpha6.1'));
assert(html.includes('id="group-settings-modal"'));
assert(app.includes('class="edited-meta">изменено'));
assert(app.includes('data-group-role'));
assert(server.includes('GROUP_MEMBER_ADDED'));
assert(server.includes('GROUP_DELETED'));
assert(server.includes('req.method==="PUT"'));
assert(server.includes('message.editedAt'));
assert(sw.includes('fibrochat-shell-v0.7.0-alpha6.1'));
console.log("Alpha 3–6.1 regression assertions: true");
