"use strict";
const fs=require("fs");
const assert=require("assert");
const read=(p)=>fs.readFileSync(p,"utf8");
const client=read("client/app.js");
const html=read("client/index.html");
const application=read("server/application.js");
const sw=read("client/sw.js");
const styles=read("client/style.css");
assert(client.includes('CLIENT_VERSION = "0.7.0-alpha7.2"'));
assert(html.includes('Conversation UI v0.7.0-alpha7.2'));
assert(html.includes('id="group-settings-modal"'));
assert(client.includes('class="edited-meta">изменено'));
assert(client.includes('data-group-role'));
assert(application.includes('GROUP_MEMBER_ADDED'));
assert(application.includes('GROUP_DELETED'));
assert(application.includes('req.method==="PUT"'));
assert(application.includes('message.editedAt'));
assert(sw.includes('fibrochat-shell-v0.7.0-alpha7.2'));
assert.ok(application.includes('/api/calls/signal'), 'Call signaling endpoint is missing');
assert.ok(application.includes('calls.audio.webrtc.v1'), 'Call capability is missing');
assert.ok(client.includes('startAudioCall'), 'Outgoing audio call client is missing');
assert.ok(client.includes('acceptIncomingCall'), 'Incoming audio call client is missing');
assert.ok(client.includes('queuedCandidates'), 'ICE candidate queue is missing');
assert.ok(client.includes('startCallTone'), 'Call tone generator is missing');
assert.ok(application.includes('/api/calls/config'), 'Call ICE config endpoint is missing');
assert.ok(application.includes('TURN_URLS'), 'TURN environment configuration is missing');
assert.ok(html.includes('id="call-modal"'), 'Call modal is missing');
assert.ok(html.includes('id="call-button"'), 'Call button is missing');
assert.ok(styles.includes('Alpha 7.1: message actions never overlap'), 'Message action layout fix is missing');
console.log("Alpha 3–7.2 regression assertions: true");
